added cell phone authorization
Maxnxi/Simple-Tracker pull request #2
Opened 2021-12-20 14:12 UTC by Maxnxi

2021-12-20 16:12 UTC, apushkarev-awg commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
> +            toggleRequestSmsCodeButton(to: true)
return

2021-12-20 16:35 UTC, YaphetS1 requested changes

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
> +        if status {
requestSmsCodeButton.isEnabled = status
requestSmsCodeButton.backgroundColor = status 
? #colorLiteral(red: 1, green: 0.7994186282, blue: 0.0005908081075, alpha: 1)
: #colorLiteral(red:

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
> +        self.cellNumber = cellNumber
leave

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
> +            if error != nil {
if let error

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
> +            } else {
В рамках if закрыть это return. else - удалить

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
> +                let storyBoard = UIStoryboard(name: "Auth", bundle: nil)
Исправить на роутинг - Coordinator/RouteController

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/CellPhoneAuthVC.swift
>          present(viewController, animated: true, completion: nil)
Исключить после добавления роутинга

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Auth/SmsCodeVC.swift
> +            if error != nil {
Error упростить

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Supervisor/MainSupervisorVC.swift
> +    var underwatchersView2: UIView?
View2?

2021-12-20 16:35 UTC, YaphetS1 commented on Simple Tracker/Flow/Supervisor/MainSupervisorVC.swift
> +        let safeArea = self.view.safeAreaLayoutGuide.layoutFrame.height
REply to func

2021-12-25 21:23 UTC, YaphetS1 approved these changes

2021-12-28 09:39 UTC, merged